FROM ubuntu:20.04

RUN apt-get update && apt-get upgrade \
    && apt-get install software-properties-common -y \
    && add-apt-repository ppa:vbernat/haproxy-2.6 \
    && apt-get update \
    && apt-get install haproxy=2.6\* -y

RUN mkdir -p /etc/haproxy/errors/
ADD ./haproxy-src/ /etc/haproxy/