FROM ubuntu:18.04

RUN apt-get update
RUN apt-get upgrade
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:vbernat/haproxy-2.4
RUN apt-get update
RUN apt-get install haproxy=2.4\* -y


RUN mkdir -p /etc/haproxy/errors/
ADD ./haproxy-src/ /etc/haproxy/
ENTRYPOINT ["haproxy", "-f", "/etc/haproxy/haproxy.cfg"]